### ISSUE TITLE
Feature Request: TODO list

### ISSUE THREAD

**Issue by sauterp** [Jayyoo2019/vite-project#1]
1. When I open the app, there should be a list of tasks.
2. I can add a new task
3. I can delete a task

**Comment by sauterp** [comment]
cool, 1. and 2. work now.
@Jayyoo2019 can you implement the delete button?

If you have a question you can ask me here about the delete button.

**Comment by Jayyoo2019** [comment]
ㅐㅏ

**Comment by Jayyoo2019** [comment]
ok

**Comment by sauterp** [comment]
deletion now works too. thanks !
